### ISSUE TITLE
error cat (100) issue after update

### ISSUE THREAD

**Issue by antest1** [antest1/GotoBrowser#100]
after 2.13 rev4 update, there were multiple report that 100 error happens frequently during supply. (like below screenshot)
could this issue be related to the recently updated touch logic? @laplamgor

![image](https://github.com/user-attachments/assets/1918c98a-6c23-462b-a19f-3936695fa9a6)

**Comment by laplamgor** [comment]
which button did they pressed?

**Comment by antest1** [comment]
the left top (supply all) button

**Comment by laplamgor** [comment]
I haven't have time yet to check. But it is probably caused by the sampling rate and framerate (Send api before the hover effect).

I cannot reproduce the issue myself with 120fps mod enabled though

**Comment by laplamgor** [comment]
https://github.com/antest1/GotoBrowser/commit/5544f7583cb7d1a7a16203dd3e514e6dee935867

Actually it was a solved old issue. I didn't have such checking in my new code.

**Comment by laplamgor** [comment]
I accidentally removed `if (displayObject.parent._onClickAll2) return;\n" `

**Comment by antest1** [comment]
oh lol I see, then I'll fix that part then update the code today (or you can make new PR if you have a time now)

**Comment by laplamgor** [comment]
I don't have time until very late tonight

**Comment by antest1** [comment]
fixed in 43f198c.
