### ISSUE TITLE
kantai3d causes client error for specific secretary

### ISSUE THREAD

**Issue by antest1** [antest1/GotoBrowser#101]
@laplamgor 

there was a report that the game getting stuck in the loading screen when a specific character (Amatsukaze Kai Ni) is set as a secretary before starting the game and kantai3d is enabled.

- kantai3d version: 4.0

here is a traceback and devtools screenshot:
```
main.js?version=6.0.0.0:46 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at _0x82d272.<computed>.<computed> [as initialize] (main.js?version=6.0.0.0:46:36)
    at _0x73e9de.<computed>.<computed> [as initialize] (main.js?version=6.0.0.0:38:177786)
    at main.js?version=6.0.0.0:12:1485278
    at t.value (mini-signals.js:93:1)
    at t._onComplete (Loader.js:617:1)
    at Loader.js:656:1
    at s (async.js:37:1)
    at e.<anonymous> (interactiveTarget.js:111:5)
    at Loader.js:639:1
    at async.js:45:1
```
![image](https://github.com/user-attachments/assets/5ac75445-e405-4123-b6dc-b26665b4dd19)

I would appreciate it if you could check on this issue when you have time!

**Comment by laplamgor** [comment]
it is a known issue. Will fix when I have time

**Comment by laplamgor** [comment]
should be fixed now (Amatsukaze Kai Ni will have 3D no effect)
