### ISSUE TITLE
Audio issue: BGM may play after leaving app

### ISSUE THREAD

**Issue by NoxArt** [antest1/GotoBrowser#11]
Version: 1.0-rev2

It happened just once, so I don't know how to reproduce it
But it basically went like this:

1) Doing some admirally stuff
2) Going to office screen
3) "Minimized" app (phone's home button -> switch to launcher)
Music kept playing
4) Went to GTB
5) Left GTB again
Music kept playing
6) Went to GTB
7) Switched to screen playing a different music (equipment?)
8) Switched back to office screen (my guess is this step is irrelevant)
9) Left GTB again
Now it was OK - no music outside app

Maybe some bug here? https://github.com/antest1/GotoBrowser/commit/990227f991911963fb83055d68e68df99124bf92#diff-1d525d6f797f3b67c32e17f3c3e45057

**Comment by NoxArt** [comment]
Maybe a duplicate of #2 but since music and voices are handled separately it may not be

**Comment by antest1** [comment]
Audio-related issues are solved from 2.0 by related system changes.
If this problem occurs again, please re-open this issue.
