### ISSUE TITLE
Audio issue: Voices not overlayed in PvP

### ISSUE THREAD

**Issue by NoxArt** [antest1/GotoBrowser#13]
Version: 1.0-rev2
Voices overlay / mutliple media players do not work in PvP, only 1 voice at the time

Happens always

I think the issue is somewhere here
https://github.com/antest1/GotoBrowser/commit/7e1cd986fa0279dfe6481da2a80d4c85aaa41238#diff-1d525d6f797f3b67c32e17f3c3e45057R925
there are probably more API paths to be added to set isBattleMode to true
(I haven't inspected the API yet)

Alternative approach might be to list only those that should have multiple players disabled, but ... it's probably better the current way

**Comment by NoxArt** [comment]
[pvpApiCallsLog.txt](https://github.com/antest1/GotoBrowser/files/3128634/pvpApiCallsLog.txt)

Looks like that's it, I think the API call that should be whitelisted is **api_req_practice**

**Comment by antest1** [comment]
Right, I'm aware of this issue and fix it in the next update.
Thanks for the report.
