### ISSUE TITLE
Audio issue: Hourlies are played twice

### ISSUE THREAD

**Issue by NoxArt** [antest1/GotoBrowser#14]
v1.0-rev3

I think it happens always for me
Not sure what other information to provide

(also the fanfair in 1-6 keeps looping, I think it should play just once, but it's a super unimportant thing probably)

**Comment by antest1** [comment]
I'll check about that.

**Comment by antest1** [comment]
Audio-related issues are solved from 2.0 by related system changes.
If this problem occurs again, please re-open this issue.

**Comment by NoxArt** [comment]
This is an amazing update, those fixes, improvements and the smoothness, wow
Thank you antest1 and @laplamgor !
