### ISSUE TITLE
Friend fleet intro disappears too quickly (clicked away?)

### ISSUE THREAD

**Issue by NoxArt** [antest1/GotoBrowser#18]
Hi,
v1.0.1-rev2

when Friend fleet appears, their intro animation is ended very quickly.
Recorded here:
https://youtu.be/AxbxDPl-zHE?t=118

Actually a person (asaTiboat) in KC Discord provided an explanation:

> this is because gotobrowser handles audio itself, instead of letting game handle it
> 
> Animation waits for audio to end, but since gotobrowser handles it, it "ends" immediately. Same happens if you have game muted in normal browser

Is this fixed in Rev3 (maybe 7b34a11e79e9a2ecf4b29d62fed8f339acbaf2d0)? Already finished E2 and no FF in E3 yet.
(btw what does "fix voice related problem" mean?)

If not ... their description makes it sound like the fix is somewhere between "difficult" and "impossible". But FF intros are amazing, if there'd be a way to fix that...

Thank you

**Comment by antest1** [comment]
I'll fix it on the next update. Thanks for the report.
(What fixed in 7b34a11 is just for event map noti, the same strategy would apply on the friend fleet voice)

**Comment by NoxArt** [comment]
Amazing, thank you

**Comment by NoxArt** [comment]
I think this is fixed, at least it seems to work now, thank you!
