### ISSUE TITLE
There still Sound secretary when come to hourly even in background mode

### ISSUE THREAD

**Issue by fajarmf94** [antest1/GotoBrowser#2]
Sorry for my bad english, i don't know this issue or bug but i just found out when the app close (not quit) and stay in background. The sound from the game automatically will gone but when it comes to secretary hourly voice, the sound just pop outso i must to turn off the voice in panel goto browser to make sure that sound not pop out in bourly voice

Don't know this bug or not

**Comment by antest1** [comment]
This seems to be a bug. I'll check about that.
Thanks for the report.

**Comment by antest1** [comment]
Audio-related issues are solved from 2.0 by related system changes.
If this problem occurs again, please re-open this issue.
