### ISSUE TITLE
Game keep re-downloading things when changing page?

### ISSUE THREAD

**Issue by pwjusticed** [antest1/GotoBrowser#20]
Everytime I switched page from one to another (for example : loading all card images from Assets page on page 1, then go to Fleet page, and back to Assets page, the game will re-downloading all those images again). Playing on Pocophone F1 running on MIUI Global 10.2.3.0 Stable (Android Pie). Is it bug in the browser cache? This is the first time I'm using this, btw. Thanks in advance!

**Comment by antest1** [comment]
If you are saying the delay for loading image, it is not downloading image but just a limitation of android webview rendering speed. (the actual data is not downloaded)

**Comment by pwjusticed** [comment]
Hmm I'm not exactly sure what happened, but the connection meter would jump to 1MB/s when it loads, as if trying to download stuff. Also I've checked the application cache but it doesn't seems to be huge, around 100MB, where usually the actual browser on PC could have about 250-300MB after everything load (including those from Assets page one by one) from scratch, zero cache. And again, I'm not exactly sure what happened, might be just me as nobody else issued the same.
