### ISSUE TITLE
Can GotoBrowser remove VPN?

### ISSUE THREAD

**Issue by HsoYo** [antest1/GotoBrowser#22]
Thanks for all of things you done and sorry for my poor English at first.

Can GotoBrowser remove VPN and using other way to monitor game?
Because the fake local VPN made the real VPN function can't work.And the real VPN is a frequently-used function for Chinese who are corssing the GFW.
So when they're using kcanotify,they'll always switch the VPNs,sometimes open the kca VPN for game,sometimes open the other VPN for youtube、twitter......
And most Chinese Kancolle players are using Japan VPN for playing the game on PC.But they can't use their VPNs with your app when gaming,only can use VPN for login DMM at the start.

Below is a famous H5 Kancolle browser in a China BBS base on your kcanotify.
I found it remove VPN function and using webview to get game packets directly.
Can GotoBrowser also changes VPN to other way in terms of codes?

APK:
http://www.uyan.pw/kcanotify/apk/Kcanotify_H5_V1.16.apk

Github:
https://github.com/qly5213/kcanotify_h5-master

Publishing page：
http://nga.178.com/read.php?tid=15331504

**Comment by NoxArt** [comment]
GTB does not require KCAnotify though, they are separate apps, I think this case should be opened here: 
https://github.com/antest1/kcanotify/issues

**Comment by antest1** [comment]
Late response, now GotoBrowser + Kcanotify does not require VPN by using Broadcast Model + PASSIVE sniffer.
