### ISSUE TITLE
This app should ask for "Storage" permission upon launch

### ISSUE THREAD

**Issue by relasm** [antest1/GotoBrowser#23]
What happened to me was that the app kept running on without saving all those cache.  Downloading everything everytime. The app used up over 30gb of my data over 2 weeks. Be aware.

**Comment by antest1** [comment]
As the app currently uses only [internal storage](https://developer.android.com/guide/topics/data/data-storage#filesInternal), the storage permission does not need to be granted.

About caching issue, I'll check about it. As it intercept the request and load from the storage instead, the real data usage statistics (from the system) can be different from the real network uses.
