### ISSUE TITLE
Audio: Friend fleets volume much lower

### ISSUE THREAD

**Issue by NoxArt** [antest1/GotoBrowser#24]
v1.0.2
Unlike #12 this happens even for speakers, not just specific earphones

While #18 has been solved, it seems that volume of Friend fleets is much lower than normal volume
Not sure what can be the cause

**Comment by antest1** [comment]
As friend fleet voice are directly played via webkit (not GotoBrowser mediaplayer), maybe the issue come from this difference.

It does not happens in my device (android 6.0), maybe can be due to the system?

**Comment by NoxArt** [comment]
Thank you, yes it's possible
My device is Android 9.0 / OneUi 1.0; in-game volume and system volume are both set to about 1/3
Not sure what other information could be helpful

**Comment by antest1** [comment]
Audio-related issue are solved from 2.0.
If this problem occurs again, please re-open this issue.
