### ISSUE TITLE
Add 21:9 layout support

### ISSUE THREAD

**Issue by plkp981056** [antest1/GotoBrowser#28]
I was just switched from a standard 16:9 device to a new device having 21:9 screen ratio (resolution is 1644x3840 
Although I have used Layout Adjustment at maximum available left and right margins of 200, part of the bottom still cannot be displayed as the layout is still too big to be viewed. Hope the later version could give a much more wider horizontal margins to deal with such device.

**Comment by antest1** [comment]
I'll fix the maximum value for screen adjustment in the next update,
