### ISSUE TITLE
 Store Email Address and save passwords in Goto browser didn't save 

### ISSUE THREAD

**Issue by fajarmf94** [antest1/GotoBrowser#3]
because this Goto is browser, everytime i log in to another browser between poi and Goto will alywas log out. well this is normal but this is not my concern and not a problem

my concern is the DMM web feature when i put email and password, cos i'm too lazy writing it in that small space, store email address and save password that featured in DMM website can't be saved in Goto Browser

can you make that feature working in Goto Browser next update?

**Comment by antest1** [comment]
Did you try using **Login Autocomplete** function?
(which is under connector selection)

You may check [manual](https://antest1.github.io/GotoBrowser/howto.html) for detail information.
