### ISSUE TITLE
Cache storage folder?

### ISSUE THREAD

**Issue by karen50630** [antest1/GotoBrowser#30]
Where's the browser's cache directory stored in?like some folder.
Cause I'm want to change some material or images in game,Can it be achieved?
Sorry for my poor English.And thank for your browser.

**Comment by antest1** [comment]
It is located in system dir (like `/data/user/0/com.antest1.gotobrowser/files/cache`)
If you have a access to system dir, you can change the resource file.

**Comment by laplamgor** [comment]
Should be resolved in https://github.com/antest1/GotoBrowser/releases/tag/v2.6
