### ISSUE TITLE
Forced relogging

### ISSUE THREAD

**Issue by NoxArt** [antest1/GotoBrowser#31]
Hi, this may be similar to #29 

When I switch from GTB to another app (or a few and back) very often I'm back at KC logging in & loading process.
Samsung Note 8 (6GB total), Android 9

My assumption is that it's Android killing it in the background, despite having more than 1GB free memory, so I blame its crappy memory management (tried every setting possible and nothing helped) and not GTB. But I'm creating the thread just in case there's something that can be done
Thank you!

**Comment by NoxArt** [comment]
Some links to threads where I tried to solve this on a system level:

https://www.reddit.com/r/GalaxyNote8/comments/cqmw1x/how_to_prevent_android_killing_apps/

https://forum.xda-developers.com/android/help/samsung-note-8-how-to-tone-killing-apps-t3946613

**Comment by NoxArt** [comment]
Maybe this could help?
https://www.reddit.com/r/GalaxyNote8/comments/cqmw1x/how_to_prevent_android_killing_apps/ex2l975/

but don't know if it's the right approach or if it would have any side effects

**Comment by antest1** [comment]
Does PIP mode solves the issue?

**Comment by NoxArt** [comment]
Firstly thank you for many great improvements!

As for this - probably not completely. The use case I have in mind is playing KanColle for a bit, then doing something else and then getting back to it - Pip obstructs a part of the screen which may conflict with some activities.
But it does solve the use case when one wants to just quickly switch to something and shortly after back.

Downside (intended or a bug?) of Pip is that music and sounds are playing always, even when pip is not focused and even if it is dismissed. I probably should have created a case for this, sorry

But I don't know if this case can be solved perfectly since I think Android's memory management is not good and mostly to blame

**Comment by antest1** [comment]
As it is not intended thing, I'll fix the sound issue in the following updates.

**Comment by antest1** [comment]
The sound issue in PIP mode is fixed on 2.1 rev1. (0473db3)
Please let me know if there are any problem.
