### ISSUE TITLE
Presets keep scrolling on multiple clicks

### ISSUE THREAD

**Issue by NoxArt** [antest1/GotoBrowser#32]
GTB v1.1 rev1
Android 9

Steps:
1) Go to Fleet screen
2) Go to Load presets
![kcPresets](https://user-images.githubusercontent.com/291595/63214654-435da880-c11b-11e9-98c1-6461fb15ae33.jpg)
3) Quickly click the down arrow multiple times

The result is that the preset list will keep scrolling down, even if you click up it will then scroll down again. Even leaving the screen and returning to it will keep scrolling it.

Workaround:
1) Click the down arrow slowly, with delays
Takes quite a long time to get to the bottom though

Fix when it happens:
1) Leave fleet screen (say HQ office)
2) Leave GTB - switch to Android launcher
3) Switch back to the game
I think all these steps need to be done, then going to Load preset will stop making it scroll

**Comment by NoxArt** [comment]
Btw please don't get discouraged by these open issues, it's still an amazing must-have app, thank you!

**Comment by antest1** [comment]
Does the problem exist for other browser like chrome?
If not happens in other browser, maybe due to script patch for preset ui (for enable preset open when non-exist ship in preset)

**Comment by NoxArt** [comment]
I will let you know tomorrow

**Comment by NoxArt** [comment]
I cannot reproduce it in Chrome

**Comment by antest1** [comment]
I think this problem is solved with hover simulation changes.
Please reopen this issue if the problem still exist.
