### ISSUE TITLE
Resizing issue

### ISSUE THREAD

**Issue by takase1121** [antest1/GotoBrowser#36]
I used the automatic resize for the browser but it doesn't work properly. As you can see, I cannot select ships from other pages
![Screenshot_2019-11-13-13-02-41-411_com antest1 gotobrowser](https://user-images.githubusercontent.com/20792268/68735309-3c5e0d80-0618-11ea-9cb7-bb699bd73efe.png)

My settings
![Screenshot_2019-11-13-12-59-24-330_com antest1 gotobrowser](https://user-images.githubusercontent.com/20792268/68734766-762e1480-0616-11ea-8807-58dabec2d31c.png)

**Comment by antest1** [comment]
Open the panel (swipe from left side or check `Show Control Panel` and click square button (below refresh button).
Two slider will appear, and use horizontal slider to fit game screen to device.

**Comment by takase1121** [comment]
Thank you! It solved my problem
