### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by kanoya1935** [antest1/GotoBrowser#37]
The English subtitles don't show up in Goto Browser even though I have them enabled. I even tried clearing the cache and uninstalling and reinstalling it, and they still don't appear

**Comment by Cheesyfof** [comment]
I can second this one; tried clearing the cache, toggling the subs and redownloading them to no avail.

**Comment by antest1** [comment]
Did you select the subtitle after download the file? (click the `English (en)` then current language will be set)

**Comment by kanoya1935** [comment]
Yes, but for some reason only Ōyodo's quest board and Akashi's improvement arsenal have subtitles. As for the rest, it's a no-go

**Comment by antest1** [comment]
does the problem still exist in the latest version?

**Comment by Cheesyfof** [comment]
iirc it works fine now :~)

**Comment by antest1** [comment]
okay, I'll close this issue. 
Please re-open the issue when the problem still exists.
