### ISSUE TITLE
Subtitles don't work.

### ISSUE THREAD

**Issue by atikabubu** [antest1/GotoBrowser#4]
Except for Ooyodo on the quest screen. My device is a Xiaomi Mi Mix 2 on Android 8, and the browser is in landscape mode, subs downloaded.

**Comment by antest1** [comment]
Make sure that the voice volume in the game is not 0, and check whether subtitle language is selected.

**Comment by atikabubu** [comment]
Voice isn't zero, and I selected the language now (wasn't obvious, consider adding a radial picker there) but the home screen still doesn't show subs.

**Comment by antest1** [comment]
You may reboot the device and try again (since it may be a temporal issue)
I'll check possible issues about that in the weekend.

(seems that there is no issue on the data, as subtitle works normally on my device)

**Comment by atikabubu** [comment]
Gave the app the internal storage permission, rebooted, and still no dice. And yes, the problem persists during exped sending, fleet picking, equipment changing, battles... Heh.

**Comment by antest1** [comment]
okay, one more question: what connector are you using?

**Comment by atikabubu** [comment]
DMM Direct, and no, I didn't, since it works fine for playing the game

**Comment by atikabubu** [comment]
Somehow the subtitles are working now, but then there's this idiocy. 
![Screenshot_2019-05-05-08-20-56-718_com antest1 gotobrowser](https://user-images.githubusercontent.com/4551435/57189442-1d671c00-6f0f-11e9-8745-ee9aa437d734.png)
