### ISSUE TITLE
main.js obfuscation

### ISSUE THREAD

**Issue by laplamgor** [antest1/GotoBrowser#40]
C2 added obfuscation to main.js
The 60fps fix, mouse hover fix and some other string replacements will no longer work,

**Comment by laplamgor** [comment]
For the 60FPS. I could inject the code change into createjs instead of main.js


For the button hover handling, it is a bit more complicated.

`main_js = main_js.replace("over:n.pointer?\"pointerover\":\"mouseover\"", "over:\"touchover\"");
main_js = main_js.replace("out:n.pointer?\"pointerout\":\"mouseout\"", "out:\"touchout\"");`
These code is being used for the global change.
It is still possible to rely on detecting `'over':_` and `'out':_` which are still paint text.

However the exception case for the port buttons is using
```
        main_js = main_js.replaceAll(
                "_.EventType\\.MOUSEUP,this\\._onMouseUp",
                "_.EventType.MOUSEDOWN,this._onMouseUp");

        main_js = main_js.replaceAll(
                "c.EventType\\.MOUSEUP,this\\._onMouseUp",
                "c.EventType.MOUSEDOWN,this._onMouseUp");
```
Will no longer work.

old main.js:
```
            e.prototype.activate = function() {
                1 != this._hit_area.buttonMode && (this._hit_area.buttonMode = !0,
                this._hit_area.on(_.EventType.MOUSEOVER, this._onMouseOver),
                this._hit_area.on(_.EventType.MOUSEOUT, this._onMouseOut),
                this._hit_area.on(_.EventType.MOUSEDOWN, this._onMouseDown),
                this._hit_area.on(_.EventType.MOUSEUP, this._onMouseUp))
            }
            ,
            e.prototype.deactivate = function() {
                this._hit_area.buttonMode = !1,
                this._hit_area.off(_.EventType.MOUSEOVER, this._onMouseOver),
                this._hit_area.off(_.EventType.MOUSEOUT, this._onMouseOut),
                this._hit_area.off(_.EventType.MOUSEDOWN, this._onMouseDown),
                this._hit_area.off(_.EventType.MOUSEUP, this._onMouseUp),
                this._onMouseOut()
            }
```

New main.js:
```
            _0x163324[_0x30d0('0x292b')][_0x30d0('0xf65')] = function() {
                0x1 != this[_0x30d0('0x16b1')][_0x30d0('0x1c49')] && (this[_0x30d0('0x16b1')][_0x30d0('0x1c49')] = !0x0,
                this[_0x30d0('0x16b1')]['on'](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0xb44')], this[_0x30d0('0x637')]),
                this[_0x30d0('0x16b1')]['on'](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0x681')], this[_0x30d0('0x81')]),
                this[_0x30d0('0x16b1')]['on'](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0x1856')], this[_0x30d0('0xf29')]),
                this[_0x30d0('0x16b1')]['on'](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0x2538')], this[_0x30d0('0x24d3')]));
            }
            ,
            _0x163324[_0x30d0('0x292b')][_0x30d0('0x254e')] = function() {
                this[_0x30d0('0x16b1')][_0x30d0('0x1c49')] = !0x1,
                this[_0x30d0('0x16b1')][_0x30d0('0x17bc')](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0xb44')], this[_0x30d0('0x637')]),
                this[_0x30d0('0x16b1')][_0x30d0('0x17bc')](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0x681')], this[_0x30d0('0x81')]),
                this[_0x30d0('0x16b1')][_0x30d0('0x17bc')](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0x1856')], this[_0x30d0('0xf29')]),
                this[_0x30d0('0x16b1')][_0x30d0('0x17bc')](_0x4862e7[_0x30d0('0x23c6')][_0x30d0('0x2538')], this[_0x30d0('0x24d3')]),
                this[_0x30d0('0x81')]();
            }
```

**Comment by antest1** [comment]
I see. 
Maybe `_0x30d0('0x1856')` matches with `MOUSEDOWN` and `_0x30d0('0x2538')` matches with `MOUSEUP`?

**Comment by laplamgor** [comment]
For this patch, yes. However the code will probably changes after every game update. Hardcoding the mapping is not ideal

**Comment by antest1** [comment]
I see, I think it would be better to deal with hardcoding now for this update.
I'll also try to find some alternative way to bypass the obfuscation.

**Comment by laplamgor** [comment]
BTW the music part and mute mode also need a fix. I am not familiar with that part.

I can create a PR for the framerate part tonight

**Comment by antest1** [comment]
I see. I'll also work on that part

**Comment by antest1** [comment]
Seems that mute function is still working on current obfuscated script, does it not work on your device?

**Comment by laplamgor** [comment]
it seems that only the exception part requires a fix but not urgent anyway.
`main_js = main_js.replaceAll("catch\\(function\\(e\\)\\{", "catch(function(e){GotoBrowser.kcs_axios_error(e.stack);");`

**Comment by laplamgor** [comment]
More info about the mouse hover,

old main.js:
```
        e.pointer = {
            down: n.pointer ? "pointerdown" : n.touch ? "touchstart" : "mousedown",
            move: n.pointer ? "pointermove" : n.touch ? "touchmove" : "mousemove",
            up: n.pointer ? "pointerup" : n.touch ? "touchend" : "mouseup",
            over: n.pointer ? "pointerover" : "mouseover",
            out: n.pointer ? "pointerout" : "mouseout"
        };
```

new main.js:
```
        _0x6aab45[_0x30d0('0x1593')] = {
            'down': _0x4a83c8[_0x30d0('0x1593')] ? _0x30d0('0x13fb') : _0x4a83c8[_0x30d0('0x28e4')] ? _0x30d0('0x1094') : _0x30d0('0x68d'),
            'move': _0x4a83c8[_0x30d0('0x1593')] ? _0x30d0('0x2400') : _0x4a83c8[_0x30d0('0x28e4')] ? _0x30d0('0x17dc') : _0x30d0('0x1ef4'),
            'up': _0x4a83c8[_0x30d0('0x1593')] ? _0x30d0('0x800') : _0x4a83c8[_0x30d0('0x28e4')] ? _0x30d0('0x27bd') : _0x30d0('0xffc'),
            'over': _0x4a83c8[_0x30d0('0x1593')] ? _0x30d0('0x170a') : _0x30d0('0x22b1'),
            'out': _0x4a83c8[_0x30d0('0x1593')] ? _0x30d0('0x1545') : _0x30d0('0xdba')
        };
```

p.s. actual files are minified

**Comment by antest1** [comment]
works done for the other patches: 84fc440
I will leave it open until this issue is completely solved.

**Comment by Tibowl** [comment]
Some speculation what can change/how to handle with the obfuscation;
The function `_0x30d0` refers to some string obfuscator. At start of main.js is a big array of all strings (base64 encoded). This array is shifted some places before being used (done by function right after that array, parse that one for shift amount, might change each update). After that function, `_0x30d0` gets defined. Might need to extract that variable name as well.

After that you can convert between stuff like "pointerdown" by using that array's indexOf and then convert to hex (or other way around, with hex -> offset in array).

I'm kinda expecting variable names to change as well, so might need some regex for it.

**Comment by antest1** [comment]
Seems that temporal works does not work for main.js update lol
Following @Tibowl, we would make some matching system for replacement.

**Comment by laplamgor** [comment]
To me, regex is easier than reverse-engineering the obfuscation function

**Comment by antest1** [comment]
seems that almost cases (like Howl, createjs, over and out) can be replaced with regex, but seems that MOUSEUP and MOUSEDOWN replacement would be hard to deal with regex?

**Comment by laplamgor** [comment]
you will need to be creative to write a very long pattern regex

**Comment by laplamgor** [comment]
You are right. It is also suggested to keep a prettified copy of main.js in a local ((publishing is illegal)) git repo. It would be easier to chase any change in the future.

**Comment by antest1** [comment]
I just did some regex works for all patches in 079445a.
now I think it will work in the next updates, let's see the further updates

**Comment by antest1** [comment]
Seems that the current patch now does not affected to the obfuscation, I'll close this issue.
