### ISSUE TITLE
Can add a switch to disable the font prefetching？

### ISSUE THREAD

**Issue by yortiss** [antest1/GotoBrowser#43]
I use a  proxy tool，it supports native cache and “replace” some cache file , like font , illustrator and so on， so it can change the font to improve reading experience（KC's default font is too thin）.

I update my gotobrowser  to 2.0 rev8， I found the font can't be replaced.
so Can add a switch to disable the font prefetching？

At last，sorry for my  bad English  and thanks for dev this app.

**Comment by antest1** [comment]
added in 2.0 rev9 (6084692).
