### ISSUE TITLE
100 Error on multiple supplies

### ISSUE THREAD

**Issue by antest1** [antest1/GotoBrowser#44]
There were some number of report that when supply the fleet with "supply all" button consecutively, 100 cat error always appears on some devices.

Example: https://twitter.com/nextto2021/status/1240559699553992706

Maybe the multiple touchover and touchout on the same button makes the problem?
Any idea for solve this issue? @laplamgor 

Below code snippet is relevant for "supply all" button.
```javascript
var o = i(3),
  r = i(1),
  s = function (t) {
    function e() {
      var e = t.call(this) || this;
      return e._onMouseOver = function () {
        e.interactive && (e.texture = o.SUPPLY_MAIN.getTexture(14), e.onMouseOver())
      }, e._onMouseOut = function () {
        e.interactive && (e.texture = o.SUPPLY_MAIN.getTexture(12), e.onMouseOut())
      }, e._onClick = function () {
        e.onClick()
      }, e.texture = o.SUPPLY_MAIN.getTexture(13), e.on(r.EventType.CLICK, e._onClick), e.on(r.EventType.MOUSEOVER, e._onMouseOver), e.on(r.EventType.MOUSEOUT, e._onMouseOut), e
    }
    return n(e, t), e.prototype.dispose = function () {
      this.onMouseOver = this._onMouseOver = null, this.onMouseOut = this._onMouseOut = null, this.onClick = this._onClick = null
    }, e.prototype.updateClickable = function (t) {
      this.interactive = this.buttonMode = t, this.texture = t ? o.SUPPLY_MAIN.getTexture(12) : o.SUPPLY_MAIN.getTexture(13)
    }, e
  }(PIXI.Sprite);
e.SupplyAllButton2 = s
```

**Comment by laplamgor** [comment]
my hover implementation includes renaming the origin events from "mouseover" to "touchover", from "mouseout" to "touchout". It is because the native mouse events name cannot be programmatically triggered/simulated due to js security protection. 

I don't have time to check it before weekend. My quick guess is this code is unable to disable the button properly after clicking once. Double clicking = re-supplying an already fully supplied fleet is not a valid API call.

You can try renaming the event names defined in the code snippet. 

In case it is really not fixable, I would suggest roll back my hover simulation code. Too many 100 cat errors can be risky and lead to a ban (?).

**Comment by antest1** [comment]
Maybe the problem can be solved when apply `proto.processTouchOverOut` for the `displayObject` has `touchover` handler? (any expecting side-effect for this?)

**Comment by laplamgor** [comment]
it will at worst break the hover simulation. You can try,

**Comment by antest1** [comment]
Currently, I fixed this problem in 5544f75 by manually disable `touchover` and `touchout` for that button. (verified on my device, waiting for the test result from the other one)

I'm not sure if there are any other points that cause 100 error 🤔

**Comment by antest1** [comment]
Seems that your guess about 100 cat error is right, the request containing empty `api_id_items` cause the server error.

Maybe clickguard mechanism on kancolle client does not work since `touchout` not called properly? (by clicking same blue supply button and there is no `touchover` event on each fleet button)

![unknown](https://user-images.githubusercontent.com/24682743/77230802-38e81d80-6bda-11ea-99e3-96edec2b1dfb.png)

**Comment by laplamgor** [comment]
The fix is working on my phone S9+. Thanks

**Comment by antest1** [comment]
I'll close this issue, please re-open this when similar problem happens.
