### ISSUE TITLE
Embedding options

### ISSUE THREAD

**Issue by treebearbb** [antest1/GotoBrowser#45]
I can't login  since last week . I hasn't change any of my set up and password  . But it keep showing username and password error and embedding options below the password box .
I have try any of the four below option and I still can't login. Pls help !
Device: Asus ROG Phone3
Android: 10
![Screenshot_20201008-123155524_1](https://user-images.githubusercontent.com/72538335/95415294-7340be80-0962-11eb-877f-d84cf7b926d6.jpg)

**Comment by antest1** [comment]
Related to this?
https://twitter.com/Senka_Viewer/status/1313874119507673096

**Comment by treebearbb** [comment]
It's kind of fixed it automatically sign into ooi.moe instead of kancolle.su

**Comment by antest1** [comment]
As this is not directly related to GotoBrowser (rather than ooi.moe issue), I'll close this issue.
