### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by DesDiv6** [antest1/GotoBrowser#49]
Hi,
This is my first time using GtB (got my hands on an old android phone with android 6.0) and I can't login via DMM direct. I'm playing from outside Japan with Gadget Server Block Bypass and Login Autocomplete enabled. When clicking Start GtB opens DMM and autocompletes in the Login, however the red Login button on DMM only refreshes the site and leads to a new login that gets autocompleted and so on. I get neither an error nor a black or white screen nor a catbomb. I'm just stuck on the login on the DMM website and can not proceed. Reinstalling GtB did not help and phone is on Japanese local time. No VPN.
Help would be greatly appreciated.

**Comment by antest1** [comment]
can you share the screenshot after the login?
