### ISSUE TITLE
About  maintenance

### ISSUE THREAD

**Issue by kancollelover** [antest1/GotoBrowser#50]
First of all thanks for your effort for creating this tool that bring lot of convinence.
 I want to consult you some questions about logging .Every time after Kancolle offcial maintanance it`s unable to log into game by GotoBrowser immediately with webpage showing"still under maintenance",
I have to wait until the next day then I can log into game. Is there any method to solve the problem?Further more can you tell me where is the cache folder?I can only find"com.antest1.kcanotify"but can`t find "com.antest1.gotobrowser" in "data"folder
Thank you very much.

**Comment by antest1** [comment]
Maybe this is due to the caching behavior or gadget server issue, are you using the default value for the gadget bypass? (`url replacement` and `http://luckyjervis.com/`)
About the cache folder, it is located in the app-specific storage, which cannot be accessed without root permission.

**Comment by antest1** [comment]
Add: when you caching on application external storage (enabled from settings),
the cache folder exists in `/storage/sdcard0/Android/data/com.antest1.gotobrowser/files/`.
