### ISSUE TITLE
Can't find font folder in cache folder

### ISSUE THREAD

**Issue by karen50630** [antest1/GotoBrowser#54]
Thank you very much,"enable caching on application external storage" this function is very important to me.
But in caching application external storage does not exist the font folder(/kcs2/resources/font).
I think it's because of "pre-fetching font file" function.
I need Replace font,so is there any other way can do it?

**Comment by antest1** [comment]
font caching behavior is currently not implemented.
I'll make work for that in the next release (to use font file in the cached folder if exists when pre-fetching disabled)

**Comment by karen50630** [comment]
Thank you so much. I really appreciate it!

**Comment by antest1** [comment]
updated in version 2.7 (185e4ef)
