### ISSUE TITLE
Browser dosen't work on Phoenix OS

### ISSUE THREAD

**Issue by GrafHammerman** [antest1/GotoBrowser#7]
Hello, i got a problem while trying to launch the browser, when i finish to configure the options of the launcher, and i press the start button, the app unexceptedly closes, not ever launching the browser, it simply crash to the home screen.

I am using Phoenix OS on a notebook.

**Comment by antest1** [comment]
Please understand that I cannot test on every OS, especially for non-standard android.
You may check whether [android webview](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=ko) is installed in your device?

**Comment by GrafHammerman** [comment]
Yeah, i have installed the android webview on my device, but the app keeps launching the "unexcepted closed" advice.

**Comment by antest1** [comment]
Does the problem still exist after the update?
