### ISSUE TITLE
crash app when use DMM driect 

### ISSUE THREAD

**Issue by mr0794** [antest1/GotoBrowser#76]
KC only can play when use ooi.me, select "dmm driect" or " kan.su" app will stop working

**Comment by laplamgor** [comment]
Please provide more information:
-Phone model
-Android version
-Webview version
-the last screen you can see before the app crash

**Comment by mr0794** [comment]
> Please provide more information: -Phone model -Android version -Webview version -the last screen you can see before the app crash

samsung tab A7 lite
android 11
[https://imgur.com/a/2j1biVn](url)

**Comment by mr0794** [comment]
no update to 2.8ver6 and it crash

**Comment by mr0794** [comment]
ok i find it because kccache proxy, change to url replacement and it normal
