### ISSUE TITLE
504 Error problem

### ISSUE THREAD

**Issue by kitio4325** [antest1/GotoBrowser#77]
![FB_IMG_1649382496736](https://user-images.githubusercontent.com/78801233/162347151-e21aaff3-5fad-4156-a7d5-777b2cd38b6d.jpg)
Hello sir
I find this problem in the morning, what should I do now?

**Comment by laplamgor** [comment]
it should be CDN server issue. I also cannot load the game page in recent hours.

**Comment by laplamgor** [comment]
Are you in shortlands? @kitio4325

**Comment by laplamgor** [comment]
seems KC server is resumed now. but downloading game asset is still very slow

**Comment by kitio4325** [comment]
Hello sir, I am shortland too. I think is DMM blocked the IP, even i can't
open the DMM app

laplamgor ***@***.***> 於 2022年4月8日 週五 09:59 寫道：

**Comment by XxJimmy122xX** [comment]
Problem come from DMM.
