### ISSUE TITLE
Black screen after login

### ISSUE THREAD

**Issue by ker052s0z** [antest1/GotoBrowser#80]
I can not enter the game after 6/8's update.
The connector is DMM direct
and it stuck on the black screen after pressing start.
Tried clear the cache but still no use.
Gotobrowser version is 2.9
and the connection setting is url replacement.

**Comment by laplamgor** [comment]
looks like URL replacement is not working after the update.

**Comment by laplamgor** [comment]
antest1 updated the default bypass server (luckyjervis).
please recreate a new ticket if the issue remains.
