### ISSUE TITLE
Abnormal screen size issue

### ISSUE THREAD

**Issue by ShowaKaeru** [antest1/GotoBrowser#86]
Dear developer,

Only when the 1st time after I install the apps and start the game by using GotoBrowser, size of the screen display normally, whereas it will display abnormally when I close the browser and re-open again, and this problem cannot be solved unless I remove and reinstall the apps. (I have tried to turn on and off all functions in the apps, but still not work)

I am appreciated if you could fix this bug, below screen capture for your reference.

Display normally only when start 1st time:
![Normal](https://github.com/antest1/GotoBrowser/assets/135502601/97000e5c-6118-4c7f-8e7f-6b949c9ca7ff)

Display abnormally when re-open the apps:
![Abnormal](https://github.com/antest1/GotoBrowser/assets/135502601/9be46674-1f61-4218-a84c-e83c79f355b4)

Apps setting:
![LNT784T0BQKFRIQD)0I_CW](https://github.com/antest1/GotoBrowser/assets/135502601/a10cb052-d1b9-4704-8562-8970a54f683a)

![VSRR@RASOH0TP2S~@D9JXIO](https://github.com/antest1/GotoBrowser/assets/135502601/b86d7d6c-d0c8-4d2a-a8d7-41d73217f0ad)

OS: Android 12

Thank you very much!

**Comment by antest1** [comment]
can you tell me what device are you using with this issue?

**Comment by ShowaKaeru** [comment]
Thank you for your prompt reply.

Sharp AQUOS R6, OS is the latest version.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antest1/GotoBrowser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 晚上11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antest1/GotoBrowser] Abnormal screen size issue (Issue #86)





 
can you tell me what device are you using with this issue?

**Comment by antest1** [comment]
let me know if same problem happens in 2.10 rev9!

**Comment by ShowaKaeru** [comment]
The problem is solved in new version! Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antest1/GotoBrowser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 晚上8:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antest1/GotoBrowser] Abnormal screen size issue (Issue #86)





 
let me know if same problem happens in 2.10 rev9!
