### ISSUE TITLE
Display position issue.

### ISSUE THREAD

**Issue by ghao87** [antest1/GotoBrowser#89]
Dear developer,
My device is vivo X Fold 2, and there is a strange display position when i'm using the internal screen. I wonder if there is any solution for this? And thank you for your brilliant works!
![_2142920195__21c70f30a611f8fb667aad9eaecd5b97_517006982_Screenshot_20230731_164619_0_wifi_0](https://github.com/antest1/GotoBrowser/assets/141020807/d0802980-8f2f-4f1f-895c-2aa5744e68f3)

**Comment by antest1** [comment]
does this issue also happens when using the app in single screen / changing the orientation?

**Comment by antest1** [comment]
let me know if same problem happens in 2.10 rev9!
