### ISSUE TITLE
Crash when trying to advance to the next node

### ISSUE THREAD

**Issue by Oradimi** [antest1/GotoBrowser#9]
I'm using GoToBrowser with the latest kcanotify on an Asus Zenfone 2 rooted to Android 7.1.2. The app works fine and cache seems to be stored properly, but sometimes when I'm trying to advance to the next node, the app crashes. Not sure why tho.

**Comment by antest1** [comment]
I also aware of this problem, and I'm finding what cause this. (maybe sound-related issue)
thanks for the report.

**Comment by antest1** [comment]
does the problem still exist on latest version?

**Comment by Oradimi** [comment]
I need further testing, I don't have much time currently, but for now it seems fixed
