### ISSUE TITLE
Screenshots are not saved

### ISSUE THREAD

**Issue by meruarc** [antest1/GotoBrowser#92]
Screenshots are not saved in 2.10rev6 and later versions.
The environment I checked is Android version 7.
It was saved normally until 2.10rev5.

We believe that perhaps recent screenshot-related fixes are affecting older Android versions.

I noticed this problem too late, so I lost the screenshots regarding current events.
I would like it to be fixed as soon as possible.

**Comment by antest1** [comment]
fixed in 2.10 rev8 update. (8f83939)
